version: "3.9"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: sh -lc "mvn clean install && mvn clean test"
    # If you need interactive debugging:
    tty: true
    stdin_open: true